// LAÇOS DE REPETIÇÃO OU EXECUTAR ACÃO VARIAS VEZES: COM A METODO (FOR) VOCÊ PODE FAZER REPETIÇÕES COM UMA CONDIÇÃO ATÉ QUE A OUTRA FOR COMPRIDA, DEFININDO VALORES E DANDO CONDIÇÕES A ELES E COM ISSO VOCÊ PODE FAZER REPETIÇÕES DE VALORES COMO O EXEMPLO DO CODIGO:
for (let i = 0; i < 10001; i++) {
    console.log(i)
}